### ISSUE TITLE
Creality Spider Hotend not fitting

### ISSUE THREAD

**Issue by RoP09** [kevinakasam/FrankEnstein-Duct#3]
Hi,

I built the BMS7 version  for the Orbiter v2 ince it says that one can be used for the Spider Hotend.

However I had to make some serious modifications in order to make it fit:
- the upper of the 2 mounting screw holes is not fitting, needs to be placed more up left (at least on my Ender 3 V2 that is)
- the right carriage mounting hole needs to be placed a little more to the right it seems (also maybe related to my Ender 3 V2)
- the spider Hotend is too big, the right side where the BL touch can be attached needed to be cut off by 3mm
- the fan guide is also much too deep for the Spider, had to cut off like 5mm to make it fit.

The upper issues I could correct by drilling a bit, but the one below  could not yet fix easily:
- the orbiter sits too far back if used with the spider hotend, around 3-4mm 
-  I have a short PTFE Tube connecting Orbiter and Spider now, but that one is now seriously bent back 

The  extruder works but I am uncertain if that bent PTFE tube affects performance as also the filament then has to travel that cruved path.

Some other issues (maybe not supported):
- I use a CR touch, but the mount is much too high if used with the spider hotend. For now 2 M4 hex nuts used as spacers do the job.
- I have a Sunon 5015 fan but the duct is much too tight fitting when the screws are mounted and I broke it easily (not the best way of attaching, maybe that could be enforced? For now I simply glued the whole duct directly to the fan which works fine it seems.

Besides that I really like the FrankEnstein-Duct :)

**Comment by nurglexp** [comment]
I'd really like to use Frank with my E3v2 and Creality Spider 500oC. Any plans to support it if the BMS7 version doesn't fit?
